lib/src/SofaGLFW/SofaGLFWBaseGUI.h
lib/src/SofaGLFW/SofaGLFWWindow.h

`GLFWwindow` is declared as a struct, not a class. It must use the same declaration in its forward declaration.

GLFWwindow is a struct, not a class

---

lib/src/SofaGLFW/SofaGLFWBaseGUI.cpp

Encountered the problem 'cause I did not set the root and just got a segfault without any info 🤫

[BaseGUI] Add check on root when createwindow()

---

lib/src/SofaGLFW/SofaGLFWBaseGUI.cpp
lib/src/SofaGLFW/SofaGLFWBaseGUI.h

Currently, when toggling to fullscreen, the fullscreen happens on the primary monitor. This may not be the desired behavior when working with multiple monitors. I added a method to the `SofaGLFWBaseGUI` to retrieve the monitor on which the current window is. The solution was taken from this [question](https://stackoverflow.com/questions/21421074/how-to-create-a-full-screen-window-on-the-current-monitor-with-glfw).

Change the selected monitor when toggling fullscreen to the current one

---

SofaImGui/CMakeLists.txt
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/ObjectColor.cpp
SofaImGui/src/SofaImGui/ObjectColor.h

In the scene graph window, the icon color depends on the object type or if there are errors or warnings. The icon itself depends on if there are errors, warnings or messages.

Icon colors in the scene graph

---

SofaImGui/src/SofaImGui/initSofaImGui.cpp
exe/Main.cpp

The log were displayed only with the runSofaGLFW app, but not with runSofa.

Capture logs

---

SofaGLFW/src/SofaGLFW/SofaGLFWGUI.h
exe/Main.cpp

It was used to forcefully load all SofaBase stuff (especially SofaBaseUtils which had RequiredPlugin)
Now that RequiredPlugin is in the core, it is much less important.
And it will be deprecated for the next release of SOFA anyway

Remove need of the (soon-to-be deprecated) module SofaBase

---

.github/workflows/ci.yml

The CI now always builds two projects:
- SofaGLFW
- SofaGLFW + SofaImGui
It allows to detect changes in SofaGLFW that can affect SofaImGui. It also allows to have up-to-date binaries with imgui.
Note the jobs are very similar. It may be factorized with reusable github workflows.

Always build both projects

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp

Assert errors while running in (pure) Debug mode in msvc
- Last argument of simpleini.SetValue() is a comment and must be prefixed with a '#' or ';'
- misplaced end of tabitem

Fix assertion errors in debug mode (msvc)

---

CMakeLists.txt

This syntax should be used to avoid CMake warnings with v22.06, more specifically, these ones:
```cmake
CMake Warning at Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake:422 (message):
Deprecated macro.  Use 'sofa_add_subdirectory(plugin ...)' instead.
Call Stack (most recent call first):
applications/projects/SofaGLFW/CMakeLists.txt:5 (sofa_add_plugin)
Adding plugin SofaGLFW
-- Install prefix: /home/busb2601/sofa/build/release/v22.06/install
-- Using X11 for window creation
CMake Warning at Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake:422 (message):
Deprecated macro.  Use 'sofa_add_subdirectory(plugin ...)' instead.
Call Stack (most recent call first):
applications/projects/SofaGLFW/CMakeLists.txt:6 (sofa_add_plugin)
CMake Warning at …
```

Changes to silence CMake warnings with v22.06

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.h

It was crashing when quitting and debugger showed it was happening when glfw was terminating.
It was trying to use nullptr callbacks (without checking it).
I guess (?) this behavior may be corrected in a later version of glfw (it would be weird anyway) but this PR fixes it for the specified version of glfw in our cmake file, namely `3.3.4`

Fix crash when GLFW is terminating

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.h
SofaGLFW/src/SofaGLFW/SofaGLFWGUI.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWGUI.h
SofaImGui/src/SofaImGui/ImGuiGUI.cpp
SofaImGui/src/SofaImGui/ImGuiGUI.h
SofaImGui/src/SofaImGui/initSofaImGui.cpp
exe/Main.cpp

Normal batch mode (batchgui) is not running any opengl rendering, so trying to measure graphical performance is impossible.
This PR adds a target number of iterations to run, quit and display the final time (simulation + rendering then)
TODO: doing the same for the "normal" runSofa (where SofaGLFW runs as a BaseGUI)

[runSOFAGLFW] add batch mode

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp

and change (add) icons for "center camera".
Restore camera menu is disabled if the view file does not exist
Question: should the camera be restored (if the .view file is present) at start-up like the other GUIs ?

[ImGUI] Add save/restore camera parameters from file

---

SofaGLFW/CMakeLists.txt
SofaGLFW/bindings/CMakeLists.txt
SofaGLFW/bindings/Module_SofaGLFW.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWGUI.cpp

Basically, allows to do
```python
import SofaGLFW
````
into [sofa]python3 scripts
Needs 
- https://github.com/sofa-framework/sofa-setup-action/pull/8
for the github action to compile successfully
(here is the result with the this branch of the action https://github.com/fredroy/SofaGLFW/actions/runs/6807991167 )

[SofaGLFW] add python3-loadable module

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp

Because error can happen in `glfwInit()`

Set error callback before init

---

SofaGLFW/src/SofaGLFW/SofaGLFWGUI.cpp

The design of `BaseGUI` is as follow:
- The destructor is protected to prevent it to be called. This is because some GUI framework objets can delete themselves, and we don't want to call the destructor again in this case (especially when on the stack).
- Class derived from `BaseGUI` call `delete this` in `closeGUI()`.
`SofaGLFWGUI::closeGUI()` did not call `delete this` in its `closeGUI` method. Hence we had memory leaks.
Replaces https://github.com/sofa-framework/SofaGLFW/pull/113

Explicit call to destructor as expected by BaseGUI design

---

SofaGLFW/src/SofaGLFW/SofaGLFWGUI.cpp

Calling terminate twice lead to a crash

remove call to terminate as it is already called by destructor

---

SofaImGui/CMakeLists.txt

Try to fix compilation error on Fedora : 
```
/usr/bin/ld: lib/libnfd.a(nfd_gtk.cpp.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
```

[ImGUI] Add PIC property when on Fedora

---

SofaImGui/CMakeLists.txt
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/UIStrings.h
SofaImGui/src/SofaImGui/windows/Settings.cpp

Both calls to `SetValue` in this PR did not have the same description string. In particular, one did not start with a comment character (# or ;), and it triggers an assert

Fix triggered assert

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.h
SofaGLFW/src/SofaGLFW/SofaGLFWGUI.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp

It is implemented in the Base class so both GUIs does restore the view if a view file is present.

[GLFW, ImGui] Automatically restore camera at startup if a view file is present

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.h

When users modify the pinned position of the windows in the interface, they may find it difficult to return to the original default view. This PR introduces a new "Reset View" option in the ImGui menu. Clicking this option will restore the window positions to their default state. The reset action is seamless, preserving all current data and avoiding the need to restart the interface. This enhancement simplifies the process of returning to the initial layout and improves user experience.
The window layout has been customized and is not in its default state. Users might struggle to return to this layout.
After clicking the "Reset View" option, the window layout has been restored to its default position, making it easy to return to the original view without losing any data.
The "Reset View" …

[ImGui] Add "Reset View" Option to Restore Default Windows Positions

---

SofaImGui/src/SofaImGui/windows/Log.cpp
SofaImGui/src/SofaImGui/windows/Log.h

Autoscroll means if a new message appears in the logs, the scrollbar will automatically scroll at the bottom to show it.

Logs: Add option for autoscroll

---

SofaImGui/src/SofaImGui/windows/Log.cpp

Always show the first line in the logs widget

Logs: Always show options

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp

https://github.com/glfw/glfw/issues/174
Solution in the quoted PR has been removed, now a hint has to be given to glfw.
It was changing to the path of the executable
So e.g, for example meshExporter was exporting the files next to the python executable (so /usr/bin... 🙄 )

MacOS: dont change workding directory when glfwinit()

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp

Otherwise, it is set only when you open the Settings window

Set global scale from the settings at startup

---

SofaImGui/src/SofaImGui/ImGuiDataWidget.cpp
SofaImGui/src/SofaImGui/ImGuiDataWidget.h

Depends on https://github.com/sofa-framework/sofa/pull/5062

Selectableitem

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.h
SofaGLFW/src/SofaGLFW/SofaGLFWWindow.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp

1- it was crashing in glfw/imgui if one quits using `Escape` key (due to erasing value in a map while iterating)
2- clean exit in imgui if one quits using the "exit" menu

[ImGui, GLFW] Fix crash when quitting

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.h
SofaGLFW/src/SofaGLFW/SofaGLFWGUI.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWWindow.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWWindow.h
exe/Main.cpp

Like Sofa.Qt, pushing 'B' key will change the background in rotations (texture_black, texture_white, black, white).
and by default  texture_black is used at startup.
- Code is a bit convoluted because of the architecture of BaseGUI and the fact that SofaGLFW wanted to manage more than 1 window (wondering about this now)
- Sofa.Qt was reloading the texture every time it was called ; here we keep in cache if the texture has already been loaded.
As glfw/imgui have the same backend, the feature is available in both GUIs

Feature: Change background (color, texture)

---

SofaGLFW/src/SofaGLFW/SofaGLFWWindow.cpp

SOFA CI does not like it on MacOS: https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-5263/CI_CONFIG=macos_clang,CI_PLUGINS=options,CI_TYPE=release/1/console

Don't use range

---

SofaGLFW/CMakeLists.txt
SofaImGui/CMakeLists.txt

This PR adds support for using some of the fetched libraries as available by an external package, so implementing a 'find or fetch' mechanism.
The goal here is to target the libraries that must be shipped otherwise with the plugin, in order to make the SofaGLFW compatible with the conda package manager and keep an available full installation of SOFA with conda (see #152).
Thus the concerned libraries for having at least a runtime package of SofaGLFW are:
- `glfw`, which is already available as a conda package on conda-forge ( https://github.com/conda-forge/glfw-feedstock )
- `nativefiledialog-extended` (or `nfd`), already available as a conda package on our sofa-framework channel ( https://anaconda.org/sofa-framework/nativefiledialog-extended ), and hopefully soon on conda-forge since a …

Use external dependencies

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.h
SofaImGui/src/SofaImGui/windows/Settings.cpp
SofaImGui/src/SofaImGui/windows/Settings.h

Very simple way to handle HiDPI fonts/icons on macOS system (tested on a macbook pro with 2x scale)
Not tested on Linux or Windows similar mechanisms
And it assumes all windows/monitors shares the same HiDPI scale (true for macOS but I suppose it could be false for Windows or Linux I guess)

Imgui: Support (macOS) HiDPI font scaling

---

SofaImGui/src/SofaImGui/windows/SceneGraph.cpp

On Ubuntu, an error message was displayed on the GUI when navigating the components on the graph widget because no ID was pushed. This PR fixes this.

Fix error coming from id not pushed

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp

Using the GUI while being on Linux and Wayland, this happens:
spamming quite a lot (at every refresh of the window...)
According to  https://github.com/glfw/glfw/issues/2621 , it is due to some unsupported features for Wayland, and the recommended approach is to force the usage of X11 instead, for the time being.
(Tested and approved)

[SofaGLFW] Force using x11 platform on Linux

---

SofaGLFW/CMakeLists.txt
SofaImGui/CMakeLists.txt

These libraries were missing from installation when building Sofa binary release package on Windows using the future Pixi pipeline.
Having a look at other plugins, this look to be the way to handle this.
Tested locally on Windows machine with the Pixi pipeline.

Install dependencies libraries glfw and nfd on Windows

---

SofaGLFW/src/SofaGLFW/BaseGUIEngine.h
SofaGLFW/src/SofaGLFW/NullGUIEngine.cpp
SofaGLFW/src/SofaGLFW/NullGUIEngine.h
SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWWindow.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.h

Relates to issue #198
This allows to use the CTRL+R to reload a scene, which I was using extensively..
For a very small need, I introduced a new function `resetCounter` in BaseGUIEngine, I do not like it but it was the only way.
This PR also cleans warnings

Shortcut to reload, plus cleaning

---

SofaGLFW/CMakeLists.txt

1) to be consistent with the fetching
2) on Ubuntu 22.04, the latest glfw package version with APT is older than 3.4. So this PR forces using the fetching mechanism to retrieve a newer version

[GLFW] Add version requirement while find_package()-ing

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/windows/SceneGraph.cpp
SofaImGui/src/SofaImGui/windows/SceneGraph.h

Same as https://github.com/sofa-framework/Sofa.Qt/pull/18
[depends-on https://github.com/sofa-framework/sofa/pull/5636]

Add minimal support for drawSelection in imGui

---

CMakeLists.txt

When adding a new plugin project into SOFA (in-tree) , there are not supposed to be ON by default.

[All] Remove ON default value for projects

---

SofaGLFW/src/SofaGLFW/BaseGUIEngine.h
SofaGLFW/src/SofaGLFW/NullGUIEngine.h
SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.h

If exit is initiated from within imgui, a crash would appear (because the mainloop is not aware that the engine has already terminated).
This PR fixes it.
EDIT: based on 
- #232

[ImGUI] Fix crash on exit
