sofa-framework/SofaGLFW

lib/CMakeLists.txt

Otherwise ImGui cannot be compiled

Remove FORCE

---

lib/SofaGLFWImgui/CMakeLists.txt
lib/SofaGLFWImgui/Style.cpp
lib/SofaGLFWImgui/Style.h
lib/src/SofaGLFW/SofaGLFWImgui.cpp

Show time in menu bar

---

lib/src/SofaGLFW/SofaGLFWImgui.cpp

Nothing very complex: it just highlights the matching components/Nodes in yellow

Introduce a search bar in the scene graph

---

README.md
lib/src/SofaGLFW/SofaGLFWBaseGUI.cpp

related to the comment https://github.com/sofa-framework/SofaGLFW/pull/26#issuecomment-1084514838

Fullscreen is enabled only when CTRL is activated

---

lib/SofaGLFWImgui/CMakeLists.txt
lib/SofaGLFWImgui/ImGuiDataWidget.cpp
lib/SofaGLFWImgui/ImGuiDataWidget.h
lib/src/SofaGLFW/SofaGLFWImgui.cpp

Format some Data

---

lib/SofaGLFWImgui/ImGuiDataWidget.cpp

Format RigidCoord types

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp

3d interaction with the mouse is possible only when not interacting with a 2d UI widget

Restore mouse behavior

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp

The only problem is that the newly opened window is not focused and may appear behind the current window (I tried but without success).
https://user-images.githubusercontent.com/10572752/166256385-045beda6-a791-461b-850d-39d3e7615743.mp4

Show Data links and open window on click

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.h

Based on https://github.com/sofa-framework/SofaGLFW/pull/39
Each window has its own member function. It's still difficult to navigate, but it's a start.

Minimal reorganization of the ImGui code

---

SofaImGui/CMakeLists.txt

Fixes https://github.com/sofa-framework/SofaGLFW/issues/44

Fix undefined reference to dlopen

---

SofaImGui/CMakeLists.txt
SofaImGui/resources/Style.cpp
SofaImGui/resources/Style.h
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.h

- Implement a configuration file to load/save settings
- Add more themes
- Option to change the theme
- Load and save the chosen theme
https://user-images.githubusercontent.com/10572752/173628774-4ad3b6cd-c987-4937-886d-c005340b4333.mp4

Change theme persistently

---

SofaImGui/CMakeLists.txt
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.h

Waits for https://github.com/sofa-framework/sofa/pull/3115 before merging
https://user-images.githubusercontent.com/10572752/177789262-4a53a3a6-933f-44cf-9d27-c455919b6700.mp4

Add menu for viewport settings

---

exe/CMakeLists.txt

Following https://github.com/sofa-framework/sofa/pull/3229

[CMake] Install exe in Sofa.GUI

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp

The checkbox filter the info message. Useful to focus only on warnings, errors etc.
There is also a "save" button to save the log into a text file

Filter info log messages and save into file

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp

Export object factory as csv file

---

.github/workflows/ci.yml

[Delete old release](https://github.com/sofa-framework/SofaGLFW/commit/b9cb26cf3c6cf6a3e729f35db52f03ee526845a2)
Similar to SofaPython3

Delete old release

---

.github/workflows/ci.yml

Similar to https://github.com/SofaDefrost/SoftRobots/pull/235

Fix softprops/action-gh-release source from master (default) to release branch

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp

To merge if https://github.com/sofa-framework/sofa/pull/4182 is merged

Integrate Tracy profiler

---

SofaImGui/CMakeLists.txt
SofaImGui/src/SofaImGui/ImGuiGUI.cpp
SofaImGui/src/SofaImGui/init.h
SofaImGui/src/SofaImGui/initSofaImGui.cpp

[SofaImgui] Allow imgui to be spawned by SofaPython3

---

SofaImGui/CMakeLists.txt
SofaImGui/bindings/CMakeLists.txt
SofaImGui/bindings/Module_SofaImGui.cpp
SofaImGui/src/SofaImGui/ImGuiGUI.cpp

[SofaImGui] add python3-loadable module

---

.github/workflows/ci.yml

- use custom action (no homebrew upgrade)
- update macos version

[MacOS] Refresh Action

---

SofaGLFW/src/SofaGLFW/initSofaGLFW.cpp
SofaImGui/src/SofaImGui/initSofaImGui.cpp

https://github.com/sofa-framework/sofa/issues/4416

Set Correct License string in the plugin(s)

---

exe/Main.cpp

Add compute BBox to set camera position prooperly when calling initVisual.

FIX runSofaGLFW black screen 

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp

Display Data associated to a component

---

SofaGLFW/src/SofaGLFW/SofaGLFWWindow.cpp

It fixes the wrong scaling of the rendering when resizing the viewport

Replace deprecated Data

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.h
SofaGLFW/src/SofaGLFW/SofaGLFWGUI.cpp
SofaGLFW/src/SofaGLFW/SofaGLFWGUI.h

Took the implementation from an issue in glfw...

Implement centerWindow()

---

SofaImGui/src/SofaImGui/AppIniFile.cpp
SofaImGui/src/SofaImGui/AppIniFile.h
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/windows/WindowState.cpp
SofaImGui/src/SofaImGui/windows/WindowState.h

for less "pollution" in the working dir

[ImGui] Put config files into a folder

---

SofaImGui/src/SofaImGui/windows/DisplayFlags.cpp

Similar problems as https://github.com/sofa-framework/SofaGLFW/pull/120

[Imgui] Fix Display Flags

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp

Same behavior in Sofa.Gui.Qt (while pressing "Step")

Allow repeating steps while the mouse button is pressed

---

.github/workflows/ci.yml

to remove the  ❌ on the frontpage

[CI] Fix deployment

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/windows/Settings.cpp

It is a pain to always resize/reposition the window at every launch.

[ImGui] QoL: Remember last window position/size

---

SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.h

Add counter for screenshots

---

SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
SofaImGui/CMakeLists.txt
SofaImGui/src/SofaImGui/ImGuiDataWidget.cpp
SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
SofaImGui/src/SofaImGui/widgets/MaterialWidget.cpp
SofaImGui/src/SofaImGui/widgets/MaterialWidget.h

https://github.com/user-attachments/assets/04294e3d-b58f-4b92-92fd-47d37870059e
Fixes https://github.com/sofa-framework/SofaGLFW/issues/169

Introduce material widget
